export { default as dom } from './dom.js'
export { default as img } from './img.js'
export { default as obj } from './obj.js'
export { default as os } from './os.js'
export { default as v2 } from './v2.js'